//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3521
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maverick.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maverick.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default Data Context Factory is &apos;{0}&apos; but no Data Context Factory with that name could be found.  Either install the Data Context Factory with the name &apos;{0}&apos; or change the &apos;{1}&apos; application setting (found in Configuration\AppSettings.config in the Web application) to another value..
        /// </summary>
        internal static string Error_DataContextFactoryNotFound {
            get {
                return ResourceManager.GetString("Error_DataContextFactoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Context Factory &apos;{0}&apos; was not imported correctly.
        /// </summary>
        internal static string Error_DataContextFactoryNotImported {
            get {
                return ResourceManager.GetString("Error_DataContextFactoryNotImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current Data Context Factory (&apos;{0}&apos;) failed to create a DataContext.
        /// </summary>
        internal static string Error_DataContextFactoryReturnedNull {
            get {
                return ResourceManager.GetString("Error_DataContextFactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Context Factory &apos;{0}&apos; was imported as a null reference.
        /// </summary>
        internal static string Error_DataContextFactoryWasNull {
            get {
                return ResourceManager.GetString("Error_DataContextFactoryWasNull", resourceCulture);
            }
        }
    }
}
